# Generated by Django 4.0.2 on 2022-02-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=60)),
                ('course', models.IntegerField(blank=True, default='', max_length=6)),
                ('instructor', models.CharField(blank=True, default='', max_length=60)),
                ('duration', models.DecimalField(decimal_places=2, default=0.0, max_digits=10000)),
                ('description', models.TextField(blank=True, default='', max_length=400)),
            ],
        ),
    ]
