# Generated by Django 4.0.2 on 2022-02-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course',
            field=models.IntegerField(blank=True, default=''),
        ),
    ]
